import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'placeholder';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export function hasValidSupabaseConfig(): boolean {
  const url = import.meta.env.VITE_SUPABASE_URL;
  const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
  if (!url || !key) return false;
  if (url === 'https://placeholder.supabase.co' || url.includes('placeholder')) return false;
  if (key === 'placeholder' || key.includes('placeholder')) return false;
  return true;
}

/**
 * Matches the public.telemetry table schema.
 * The ESP32 sends only { pir_detected: boolean }.
 * created_at is auto-stamped by Postgres — the ESP32 never needs to send it.
 * id is auto-generated by Postgres.
 *
 * Temperature, humidity, LED state, buzzer, LCD text, and node_id are
 * NOT stored in this table — they are derived from scenario simulation
 * on the frontend or handled locally by the ESP32.
 */
export interface TelemetryRow {
  id: string;
  pir_detected: boolean;
  created_at: string;
}

/**
 * Full IoT sensor state used throughout the React UI.
 * In live mode: pir_detected + lastUpdated come from real hardware via Supabase.
 * All other fields (temperature, humidity, lcdText, ledState, buzzerActive, nodeId)
 * are derived from the active scenario simulation — the ESP32 does not send them.
 */
export interface IotSensorState {
  connected: boolean;
  pirDetected: boolean;
  temperature: number | null;
  humidity: number | null;
  lcdText: string;
  ledState: 'green' | 'red';
  buzzerActive: boolean;
  nodeId: string;
  lastUpdated: string | null;
}

export const defaultIotState: IotSensorState = {
  connected: false,
  pirDetected: false,
  temperature: null,
  humidity: null,
  lcdText: 'Showing: City Health Score',
  ledState: 'green',
  buzzerActive: false,
  nodeId: 'esp32-node-01',
  lastUpdated: null,
};

/**
 * Converts a row from public.telemetry into a partial IotSensorState.
 *
 * Only pir_detected and created_at are sourced from the database row.
 * The caller (App.tsx displayIotState merge) is responsible for filling in the
 * remaining fields from the active scenario simulation, which is the correct
 * behaviour — the ESP32 does not send temperature, humidity, etc.
 *
 * ledState and buzzerActive are derived from pir_detected so the UI stays
 * consistent with the hardware PIR reading even without a DHT11 sensor.
 */
export function telemetryRowToState(row: TelemetryRow): IotSensorState {
  return {
    connected: true,
    pirDetected: row.pir_detected,
    // LED and buzzer are driven by PIR state (hardware handles them locally;
    // this mirrors that behaviour in the dashboard).
    ledState: row.pir_detected ? 'red' : 'green',
    buzzerActive: row.pir_detected,
    lcdText: row.pir_detected ? 'MOTION DETECTED' : 'Status: Normal',
    // temperature, humidity, nodeId are not in the telemetry table.
    // App.tsx merges these from the scenario simulation on top of this state.
    temperature: null,
    humidity: null,
    nodeId: 'esp32-node-01',
    lastUpdated: row.created_at,
  };
}
