import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'placeholder';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export function hasValidSupabaseConfig(): boolean {
  const url = import.meta.env.VITE_SUPABASE_URL;
  const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
  if (!url || !key) return false;
  if (url === 'https://placeholder.supabase.co' || url.includes('placeholder')) return false;
  if (key === 'placeholder' || key.includes('placeholder')) return false;
  return true;
}

/**
 * Matches the public.iot_telemetry table schema.
 * The ESP32 sends: pir_detected, distance, temp, humidity.
 * created_at and id are auto-generated by Postgres.
 */
export interface TelemetryRow {
  id: string;
  pir_detected: boolean;
  distance: number | null;  // cm from HC-SR04; -1 or null = out of range
  temp: number | null;      // °C from DHT11
  humidity: number | null;  // % from DHT11
  created_at: string;
}

/**
 * Full IoT sensor state used throughout the React UI.
 * In live mode: all fields come from real hardware via Supabase.
 * In simulation mode: fields are derived from the active scenario.
 */
export interface IotSensorState {
  connected: boolean;
  pirDetected: boolean;
  temperature: number | null;
  humidity: number | null;
  distance: number | null;   // cm from HC-SR04 ultrasonic sensor
  lcdText: string;
  ledState: 'green' | 'red';
  buzzerActive: boolean;
  nodeId: string;
  lastUpdated: string | null;
}

export const defaultIotState: IotSensorState = {
  connected: false,
  pirDetected: false,
  temperature: null,
  humidity: null,
  distance: null,
  lcdText: 'Showing: City Health Score',
  ledState: 'green',
  buzzerActive: false,
  nodeId: 'esp32-node-01',
  lastUpdated: null,
};

/**
 * Converts a row from public.iot_telemetry into an IotSensorState.
 *
 * All sensor values (pir_detected, distance, temp, humidity) are sourced
 * directly from the database row — reflecting real ESP32 hardware readings.
 * ledState and buzzerActive mirror the hardware: they are driven by pir_detected.
 */
export function telemetryRowToState(row: TelemetryRow): IotSensorState {
  const detected = row.pir_detected;
  const dist = row.distance ?? null;

  // Build LCD text to mirror the physical LCD on the ESP32
  let lcdText: string;
  if (detected) {
    lcdText = dist !== null && dist > 0
      ? `ALERT! ${dist.toFixed(1)}cm`
      : 'ALERT! Object Close';
  } else {
    lcdText = dist !== null && dist > 0
      ? `Dist: ${dist.toFixed(1)}cm`
      : 'Status: Normal';
  }

  return {
    connected: true,
    pirDetected: detected,
    ledState: detected ? 'red' : 'green',
    buzzerActive: detected,
    lcdText,
    temperature: row.temp ?? null,
    humidity: row.humidity ?? null,
    distance: dist,
    nodeId: 'esp32-node-01',
    lastUpdated: row.created_at,
  };
}
