import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'placeholder';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export function hasValidSupabaseConfig(): boolean {
  const url = import.meta.env.VITE_SUPABASE_URL;
  const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
  if (!url || !key) return false;
  if (url === 'https://placeholder.supabase.co' || url.includes('placeholder')) return false;
  if (key === 'placeholder' || key.includes('placeholder')) return false;
  return true;
}

/**
 * Matches the public.iot_telemetry table schema.
 * The ESP32 sends: pir_detected, temp (°C from DHT11), humidity (% from DHT11).
 * created_at is auto-stamped by Postgres.
 * id is auto-generated by Postgres.
 */
export interface TelemetryRow {
  id: string;
  pir_detected: boolean;
  temp: number | null;
  humidity: number | null;
  created_at: string;
}

/**
 * Full IoT sensor state used throughout the React UI.
 * In live mode: pir_detected, temp, humidity, and lastUpdated come from
 * real hardware (ESP32 + DHT11) via Supabase Realtime.
 * ledState, buzzerActive, lcdText, and nodeId are derived locally.
 */
export interface IotSensorState {
  connected: boolean;
  pirDetected: boolean;
  temperature: number | null;
  humidity: number | null;
  lcdText: string;
  ledState: 'green' | 'red';
  buzzerActive: boolean;
  nodeId: string;
  lastUpdated: string | null;
}

export const defaultIotState: IotSensorState = {
  connected: false,
  pirDetected: false,
  temperature: null,
  humidity: null,
  lcdText: 'Showing: City Health Score',
  ledState: 'green',
  buzzerActive: false,
  nodeId: 'esp32-node-01',
  lastUpdated: null,
};

/**
 * Converts a row from public.iot_telemetry into a full IotSensorState.
 *
 * pir_detected, temp, and humidity come directly from the hardware row.
 * ledState and buzzerActive are derived from pir_detected to mirror the
 * behaviour the ESP32 handles locally on its own GPIO pins.
 */
export function telemetryRowToState(row: TelemetryRow): IotSensorState {
  return {
    connected: true,
    pirDetected: row.pir_detected,
    // Live DHT11 readings — null if the sensor didn't send a value this cycle
    temperature: row.temp ?? null,
    humidity: row.humidity ?? null,
    // LED and buzzer mirror the PIR state (matches hardware behaviour)
    ledState: row.pir_detected ? 'red' : 'green',
    buzzerActive: row.pir_detected,
    lcdText: row.pir_detected ? 'MOTION DETECTED' : 'Status: Normal',
    nodeId: 'esp32-node-01',
    lastUpdated: row.created_at,
  };
}
