/*
  # Create public.telemetry table for ESP32 PIR sensor telemetry

  ## Purpose
  This table is the authoritative destination for real ESP32 hardware telemetry.
  The ESP32 sends a minimal JSON payload via Supabase PostgREST (no Edge Function
  required in the hot path):

      POST /rest/v1/telemetry
      Content-Type: application/json
      apikey: <anon key>
      Authorization: Bearer <anon key>

      { "pir_detected": true }
      or
      { "pir_detected": false }

  The frontend subscribes to this table via Supabase Realtime and reflects new
  rows instantly without a page refresh.

  ## Schema
  - id           uuid, primary key, auto-generated by Postgres
  - pir_detected boolean, NOT NULL — PIR OUT → D13 on ESP32 (HIGH = motion)
  - created_at   timestamptz, NOT NULL — auto-stamped by Postgres on INSERT,
                 so the ESP32 does NOT need to send a timestamp

  ## Security (RLS)
  - anon role can INSERT  → ESP32 uses the public anon key to POST telemetry
  - anon role can SELECT  → React dashboard reads rows using the same anon key
  - service_role key is NEVER needed by the ESP32 or the frontend
  - UPDATE and DELETE are intentionally omitted (append-only log)

  ## Realtime
  The table is added to supabase_realtime publication so the frontend's
  postgres_changes subscription fires on every INSERT.
*/

-- ─── Table ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.telemetry (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  pir_detected boolean     NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- ─── Row Level Security ───────────────────────────────────────────────────────
ALTER TABLE public.telemetry ENABLE ROW LEVEL SECURITY;

-- ESP32 (anon key) can INSERT telemetry rows
DROP POLICY IF EXISTS "anon_insert_telemetry" ON public.telemetry;
CREATE POLICY "anon_insert_telemetry"
  ON public.telemetry
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- React dashboard (anon key) can SELECT telemetry rows
DROP POLICY IF EXISTS "anon_select_telemetry" ON public.telemetry;
CREATE POLICY "anon_select_telemetry"
  ON public.telemetry
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- ─── Realtime ─────────────────────────────────────────────────────────────────
-- Adds the table to the default Supabase Realtime publication so that
-- postgres_changes subscriptions on this table work from the frontend.
ALTER PUBLICATION supabase_realtime ADD TABLE public.telemetry;

-- ─── Index ────────────────────────────────────────────────────────────────────
-- Efficient "latest first" queries used by the dashboard on initial load.
CREATE INDEX IF NOT EXISTS idx_telemetry_created_at
  ON public.telemetry (created_at DESC);
